server:
  servlet:
    encoding:
      charset: utf-8         # ?? ? ??? UTF-8 ???? ???? ?? ? ????? ??? ??? ??
      force: true            # ??? UTF-8 ???? ??, ?????? ?? ???? ?????? ???? UTF-8? ??
  port: 8080                 # ??? 8080 ???? ????? ??

spring:
  mustache:
    servlet:
      expose-session-attributes: true  # Mustache ????? ?? ??? ??? ? ??? ??
      expose-request-attributes: true  # Mustache ????? ?? ??? ??? ? ??? ??
  datasource:
    driver-class-name: org.h2.Driver    # ?????? ????? H2 DB? ??
    url: jdbc:h2:mem:test;MODE=MySQL    # H2 ???? ??????? MySQL ?? ??? ?? (????)
    username: sa                        # ?????? ?? ? ?? ??? ??
    password:                           # ?????? ?? ???? (?? ??)
  h2:
    console:
      enabled: true   # H2 ?????? ??? ????? ?????? ??????? ??? ? ??? ?
  sql:
    init:
      data-locations:
        - classpath:db/data.sql  # ?????? ??? ? ??? ??? ?? SQL ??? ?? (data.sql)
  jpa:
    hibernate:
      ddl-auto: create            # ??????? ??? ? ?????? ???? ???? ??
    show-sql: true                # Hibernate? ???? SQL ??? ??? ??
    properties:
      hibernate:
        format_sql: true          # ???? SQL ??? ????? ?? ?? ??
    defer-datasource-initialization: true  # ?????? ???? ????? ???? JPA ?? ?? ??? ???

  output:
    ansi:
      enabled: always  # ?? ?? ? ANSI ??? ?? ????? ?? (??? ?? ??? ? ?? ?? ??)

  config:
    title: MY APPLICATION
    author: MOSEOH